### ISSUE TITLE
Think of sensible sampling strategies and implement them into our framework

### ISSUE THREAD

**Issue by Grutschus** [Grutschus/human-fall-detection#21]
Depending on the insights gained from #20, we need to create different sampling strategies that might make more sense than the `UniformSamplingStrategy`

**Comment by emiresenov** [comment]
Update: we've implemented three sampling strategies offline and tested them [locally](https://github.com/Grutschus/human-fall-detection/blob/sampling-and-labelling-strategies/sampling/Sample%20notebook.ipynb)). I had some issues getting dvc to work on my computer, so we've only done local tests. 

What remains to do is: remove the iteration cap from [the sample outputter](https://github.com/Grutschus/human-fall-detection/blob/sampling-and-labelling-strategies/sampling/sampler.py#L193), and try running the sampler with dvc to make sure that it works.
