### ISSUE TITLE
Create a preprocessing script to cut up the High Quality Fall Dataset

### ISSUE THREAD

**Issue by Grutschus** [Grutschus/human-fall-detection#9]
Develop a Python script that takes in the raw dataset as downloaded from the internet (High Quality Fall Dataset) and cuts it up into segments of equal length. It should also save the segment in a way that is compatible with the `VideoDataset` from MMAction. Also output the annotation files in a correct format.

Need to find out this first:
#11

**Comment by OlaKarrar** [comment]
The completed script can be located within the "script" folder of the repository, named "trim_video.py."
